---
title: alert
name: alert
collection: molecules
notes: |
  ##### Usage : `alert`
---
<div class="alert alert-info" style="margin-bottom:0;">
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h3>
        Séance d'information ce mardi 30 Août à 18h30
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
        <a href="http://www.sawi.com/fr/seances-dinformation/form/?uid=215" class="btn btn-primary btn-block">Inscription</a>
    </div>
    <div class="col-sm-6">
        <p>
          <strong>Venez poser vos questions et discuter avec les responsables du cours à <a href="https://goo.gl/maps/cxR4nmTFRn42">La Maison de la communication, Lausanne</a>
        </p>
      </div>
    </div>
  </div>
</div>
