---
title: header
name: header
collection: molecules
notes: |
  ##### Usage : `header`
  ##### Options :
  - **cours** - object
---
<header class="header">
  <div class="container">
    <div class="header-container">
      <img src="/build/img/logo.svg" alt="" style="max-height:80px;"/>
      <h3 class="text-right header-title">
          <a href="http://www.sawi.com/fr/" target="_blank" class="header-link"><span class="hidden-xs">sawi</span>.com <img src="/build/img/icon-external-link.svg" alt=""/></a>
      </h3>
    </div>
  </div>
</header>
