---
title: inline-cta
name: inline-cta
collection: molecules
notes: |
  ##### Usage : `inline-cta`
  ##### Options :
  - **cours** - object
---
<div class="inline-cta">
  <p class="inline-cta-container">
    <a href="{{ cours.conversionurl }}" class="btn btn-primary btn-lg" id="cta-inline">Intéressé ?</a><br/>
    <span class="inline-cta-legend">Recevez le dossier complet par email</span>
  </p>
</div>
