---
title: mega-cta
name: mega-cta
collection: molecules
notes: |
  ##### Usage : `mega-cta`
  ##### Options :
  - **cours** - object
---
<div class="fixed-cta">
  <div class="container">
    <p class="fixed-cta-container">
      <span class="fixed-cta-legend">Recevez le dossier complet par email</span>
      <a href="{{ cours.conversionurl }}" class="btn btn-primary btn-lg">Intéressé ?</a>
    </p>
  </div>
</div>
