---
title: mega-cta
name: mega-cta
collection: molecules
notes: |
  ##### Usage : `mega-cta`
  ##### Options :
  - **url** - string
---
<div class="fixed-cta">
  <div class="container">
    <p class="fixed-cta-container">
      <span class="fixed-cta-legend">Recevez le dossier complet par email</span>
      <a href="https://confirmsubscription.com/h/r/3A944A659E9492E0" class="btn btn-primary btn-lg">Intéressé ?</a>
    </p>
  </div>
</div>
